# Generated by Django 5.2.8 on 2026-06-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriacaoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_criacao', models.CharField(max_length=100)),
                ('sistema_criacao', models.CharField(blank=True, max_length=120)),
                ('producao_organica', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criacoes_animais', to='produtores.produtor')),
            ],
        ),
        migrations.CreateModel(
            name='Avicultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(choices=[('galinha', 'Galinha'), ('pato', 'Pato'), ('codorna', 'Codorna')], max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('finalidade', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('criacao_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aviculturas', to='criacao_animal.criacaoanimal')),
            ],
        ),
    ]
