# Generated by Django 5.2.8 on 2026-06-02 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtor_nome', models.CharField(blank=True, max_length=180)),
                ('produtor_cpf', models.CharField(blank=True, max_length=14)),
                ('tecnico_responsavel', models.CharField(blank=True, max_length=180)),
                ('data', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='produtores.produtor')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
