# Generated by Django 5.2.8 on 2026-06-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cultura', models.CharField(max_length=120)),
                ('subtipo', models.CharField(blank=True, choices=[('mandioca', 'Mandioca'), ('culturas_industriais', 'Culturas industriais'), ('outras_culturas', 'Outras culturas')], max_length=40)),
                ('area_plantada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unidade_area', models.CharField(default='ha', max_length=20)),
                ('quantidade_produzida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unidade_producao', models.CharField(default='kg', max_length=20)),
                ('formula_calculo', models.CharField(default='quantidade_produzida / area_plantada', max_length=120)),
                ('resultado_calculo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('producao_organica', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culturas', to='produtores.produtor')),
            ],
            options={
                'ordering': ['nome_cultura'],
            },
        ),
    ]
