# Generated by Django 5.2.8 on 2026-06-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_localizacao', models.CharField(choices=[('zona_rural', 'Zona Rural'), ('zona_urbana', 'Zona Urbana')], max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('comunidade', models.CharField(blank=True, max_length=150)),
                ('ramal', models.CharField(blank=True, max_length=120)),
                ('ponto_referencia', models.CharField(blank=True, max_length=255)),
                ('acesso', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produtor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localizacao', to='produtores.produtor')),
            ],
        ),
    ]
