# Generated by Django 5.2.8 on 2026-06-02 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=12, unique=True)),
                ('modelo', models.CharField(max_length=120)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('ano', models.CharField(blank=True, max_length=4)),
                ('cor', models.CharField(blank=True, max_length=60)),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('quilometragem', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Em uso', 'Em uso'), ('Em manutenção', 'Em manutenção'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=30)),
                ('gasolina', models.PositiveSmallIntegerField(default=100)),
                ('observacoes', models.TextField(blank=True)),
                ('responsavel_cadastro', models.CharField(blank=True, max_length=150)),
                ('finalidade_uso', models.CharField(blank=True, max_length=255)),
                ('data_retirada', models.DateTimeField(blank=True, null=True)),
                ('historico_uso', models.JSONField(blank=True, default=list)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tecnico_em_uso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_em_uso', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
