# Generated by Django 5.2.8 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtor",
            name="publico",
            field=models.CharField(
                choices=[
                    ("homem_jovem", "Homem jovem - 20 a 29 anos"),
                    ("homem_adulto", "Homem adulto - 30 a 59 anos"),
                    ("mulher_jovem", "Mulher jovem - 20 a 29 anos"),
                    ("mulher_adulta", "Mulher adulta - 30 a 59 anos"),
                    ("jovem", "Jovem - 13 anos"),
                    ("idoso", "Idoso - 60 anos"),
                ],
                max_length=20,
            ),
        ),
    ]
