# Generated by Django 5.2.8 on 2026-06-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtores', '0001_initial'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carteira', models.CharField(max_length=80)),
                ('tipo_carteira', models.CharField(max_length=80)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('orgao_emissor', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteiras', to='produtores.produtor')),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteiras', to='registro.registro')),
            ],
            options={
                'unique_together': {('produtor', 'numero_carteira')},
            },
        ),
    ]
