# Generated by Django 5.2.8 on 2026-06-02 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtor_nome', models.CharField(blank=True, max_length=180)),
                ('tecnico_nome', models.CharField(blank=True, max_length=180)),
                ('dia_semana', models.CharField(max_length=30)),
                ('turno', models.CharField(default='manha', max_length=20)),
                ('horario_saida_manha', models.CharField(blank=True, max_length=20)),
                ('horario_entrada_manha', models.CharField(blank=True, max_length=20)),
                ('horario_saida_tarde', models.CharField(blank=True, max_length=20)),
                ('horario_entrada_tarde', models.CharField(blank=True, max_length=20)),
                ('atividade', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('recomendacoes', models.TextField(blank=True)),
                ('cor', models.CharField(blank=True, max_length=20)),
                ('semana', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cronogramas_criados', to=settings.AUTH_USER_MODEL)),
                ('produtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='produtores.produtor')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_tecnicas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
