# Generated by Django 5.2.8 on 2026-06-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participa_paa', models.BooleanField(default=False)),
                ('perfil', models.CharField(blank=True, max_length=120)),
                ('dados_propriedade', models.TextField(blank=True)),
                ('documentos_entregues', models.JSONField(blank=True, default=list)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produtor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paa', to='produtores.produtor')),
            ],
        ),
    ]
