# Generated by Django 5.2.8 on 2026-06-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(max_length=60, unique=True)),
                ('data_registro', models.DateField()),
                ('possui_carteira', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado'), ('suspenso', 'Suspenso')], default='rascunho', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produtor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro', to='produtores.produtor')),
            ],
        ),
    ]
