# Generated by Django 5.2.8 on 2026-06-02 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtor_nome', models.CharField(blank=True, max_length=180)),
                ('produtor_cpf', models.CharField(blank=True, max_length=14)),
                ('tipo_documento', models.CharField(max_length=120)),
                ('gerado_por_nome', models.CharField(blank=True, max_length=180)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gerados', to=settings.AUTH_USER_MODEL)),
                ('produtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_emitidos', to='produtores.produtor')),
            ],
        ),
    ]
