# Generated by Django 5.2.8 on 2026-06-01 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieAbelha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(max_length=120)),
                ('nome_cientifico', models.CharField(max_length=160)),
                ('tipo_abelha', models.CharField(max_length=120)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome_popular'],
            },
        ),
        migrations.CreateModel(
            name='Meliponicultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_colmeias', models.PositiveIntegerField(default=0)),
                ('producao_mel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unidade_producao', models.CharField(default='kg', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meliponiculturas', to='meliponicultura.especieabelha')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meliponiculturas', to='produtores.produtor')),
            ],
        ),
    ]
